services:
  db:
    image: postgres:18.1
    restart: always
    shm_size: 1024mb
    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${ENV_PASSWORD}
      POSTGRES_USER: ${ENV_USER}
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8070:8080"

volumes:
  postgres_data: