spring:
  application:
    name: Anime-Service
  web:
    error:
      include-stacktrace: on_param
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:animes}
    username: ${LOCAL_USER:sa}
    password: ${LOCAL_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: ${DB_DIALECT:}

server:
  servlet:
    context-path: /
